### PR TITLE
Add reset() StateMachine. It resets the state machine to Closed state.

### PR DESCRIPTION
**Pull request by fredxia**
Sometimes it is necessary to force the reset of state machine because the caller may have some external information that warrants such a reset.

### CODE REVIEW

**Comment by dmexe** [comment]
Thanks for work. But PL has warnning https://app.circleci.com/pipelines/github/dmexe/failsafe-rs/1024/workflows/1fee5e85-c989-4516-bd8a-7952821c297c/jobs/1891 from the linter. It should be fixed before I merge the PL.

**Comment by fredxia** [comment]
> Thanks for work. But PL has warnning https://app.circleci.com/pipelines/github/dmexe/failsafe-rs/1024/workflows/1fee5e85-c989-4516-bd8a-7952821c297c/jobs/1891 from the linter. It should be fixed before I merge the PL.

Hi, I fixed the fmt issues. Please check again. Thanks very much.

**Review by dmexe — APPROVED** [review]

**Comment by fredxia** [comment]
Hi Dmitry,

When my project cargo pulls failsafe-rs with "failsafeit seems the code
still does not have the reset() method.

When I pull directly from github it does have reset().

Can you please tag a new version, e.g. v1.2.0?

Thanks.


Fred Xia

**Comment by dmexe** [comment]
Hi, done.

**Pull request merged**
